var nameList = [
    'Time', 'Past', 'Future', 'Dev',
    'Fly', 'Flying', 'Soar', 'Soaring', 'Power', 'Falling',
    'Fall', 'Jump', 'Cliff', 'Mountain', 'Rend', 'Red', 'Blue',
    'Green', 'Yellow', 'Gold', 'Demon', 'Demonic', 'Panda', 'Cat',
    'Kitty', 'Kitten', 'Zero', 'Memory', 'Trooper', 'XX', 'Bandit',
    'Fear', 'Light', 'Glow', 'Tread', 'Deep', 'Deeper', 'Deepest',
    'Mine', 'Your', 'Worst', 'Enemy', 'Hostile', 'Force', 'Video',
    'Game', 'Donkey', 'Mule', 'Colt', 'Cult', 'Cultist', 'Magnum',
    'Gun', 'Assault', 'Recon', 'Trap', 'Trapper', 'Redeem', 'Code',
    'Script', 'Writer', 'Near', 'Close', 'Open', 'Cube', 'Circle',
    'Geo', 'Genome', 'Germ', 'Spaz', 'Shot', 'Echo', 'Beta', 'Alpha',
    'Gamma', 'Omega', 'Seal', 'Squid', 'Money', 'Cash', 'Lord', 'King',
    'Duke', 'Rest', 'Fire', 'Flame', 'Morrow', 'Break', 'Breaker', 'Numb',
    'Ice', 'Cold', 'Rotten', 'Sick', 'Sickly', 'Janitor', 'Camel', 'Rooster',
    'Sand', 'Desert', 'Dessert', 'Hurdle', 'Racer', 'Eraser', 'Erase', 'Big',
    'Small', 'Short', 'Tall', 'Sith', 'Bounty', 'Hunter', 'Cracked', 'Broken',
    'Sad', 'Happy', 'Joy', 'Joyful', 'Crimson', 'Destiny', 'Deceit', 'Lies',
    'Lie', 'Honest', 'Destined', 'Bloxxer', 'Hawk', 'Eagle', 'Hawker', 'Walker',
    'Zombie', 'Sarge', 'Capt', 'Captain', 'Punch', 'One', 'Two', 'Uno', 'Slice',
    'Slash', 'Melt', 'Melted', 'Melting', 'Fell', 'Wolf', 'Hound',
    'Legacy', 'Sharp', 'Dead', 'Mew', 'Chuckle', 'Bubba', 'Bubble', 'Sandwich', 'Smasher', 'Extreme', 'Multi', 'Universe', 'Ultimate', 'Death', 'Ready', 'Monkey', 'Elevator', 'Wrench', 'Grease', 'Head', 'Theme', 'Grand', 'Cool', 'Kid', 'Boy', 'Girl', 'Vortex', 'Paradox'
  ];
  export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
};



export function generateRandomMessage() {
  const messages = [
    "Hello, how are you today?",
    "What's your favorite color?",
    "Do you have any plans for the weekend?",
    "Have you watched any good movies lately?",
    "How's the weather where you are?",
    "What's your favorite hobby?",
    "Do you prefer cats or dogs?",
    "Tell me something interesting about yourself.",
    "If you could travel anywhere in the world, where would you go?",
    "What's the best book you've ever read?",
    "What's your dream job?",
    "What's the most adventurous thing you've ever done?",
    "Do you enjoy cooking?",
    "What's your favorite type of music?",
    "What's your earliest childhood memory?",
    "What's one thing on your bucket list?",
    "What's your favorite season?",
    "If you could have any superpower, what would it be?",
    "What's the best piece of advice you've ever received?",
    "What's your favorite food?",
    "Do you believe in aliens or extraterrestrial life?",
    "What's your favorite thing about yourself?",
    "What's your biggest pet peeve?",
    "If you could meet any historical figure, who would it be?",
    "What's your favorite way to relax?",
    "Do you prefer city life or country life?",
    "What's your favorite quote?",
    "What's one thing you couldn't live without?",
    "What's your favorite childhood TV show?",
    "What's your favorite board game?",
    "What's the most memorable trip you've ever taken?",
    "What's your favorite dessert?",
    "Do you enjoy exercising?",
    "What's your favorite holiday?",
    "If you could have dinner with any celebrity, who would it be?",
    "What's your biggest fear?",
    "What's one thing you want to accomplish this year?",
    "What's your favorite thing to do on a lazy day?",
    "What's your favorite type of movie?",
    "What's one thing you're grateful for today?",
    "Do you have any hidden talents?",
    "What's your favorite way to spend time with friends?",
    "What's the best gift you've ever received?",
    "What's your favorite type of art?",
    "What's one thing you've always wanted to learn?",
    "What's your favorite childhood memory?",
    "What's one piece of technology you couldn't live without?",
    "What's your favorite thing to do outdoors?",
    "Do you enjoy traveling?",
    "What's your favorite thing about your job or school?",
    "What's your favorite way to start the day?",
    "What's one thing that always makes you smile?",
    "What's the most interesting place you've ever been?",
    "What's your favorite thing to do in your free time?",
    "What's your favorite animal?",
    "What's one thing you're proud of?",
    "What's your favorite way to spend a rainy day?",
    "What's your favorite childhood toy?",
    "What's your favorite way to stay active?",
    "What's one thing you want to learn more about?",
    "What's your favorite thing about the place you live?",
    "What's your favorite memory from high school or college?",
    "What's the most adventurous food you've ever tried?",
    "What's your favorite way to learn new things?",
    "What's your favorite thing about your family?",
    "What's one thing you want to improve about yourself?",
    "What's your favorite type of movie genre?",
    "What's your favorite thing to do in the summer?",
    "What's the best concert you've ever been to?",
    "What's one thing you're looking forward to in the future?",
    "What's your favorite thing to do on a long car ride?",
    "What's your favorite thing about yourself?",
    "What's your favorite way to spend time alone?",
    "What's your favorite way to celebrate your birthday?",
    "What's your favorite way to stay motivated?",
    "What's the most meaningful gift you've ever given?",
    "What's one thing that always makes you laugh?",
    "What's your favorite way to express yourself?",
    "What's your favorite thing about the holidays?",
    "What's your favorite type of cuisine?",
    "What's one thing you want to achieve in the next five years?",
    "What's your favorite thing to do on a Friday night?",
    "What's your favorite childhood book?",
    "What's your favorite way to unwind after a long day?",
    "What's the most interesting job you've ever had?",
    "What's your favorite way to learn new things?",
    "What's your favorite thing to do on a sunny day?",
    "What's your favorite way to meet new people?",
    "What's one thing you want to change about the world?",
    "What's your favorite thing about yourself?",
    "What's your favorite way to stay organized?",
    "What's your favorite thing to do in the winter?",
    "What's the most unusual food you've ever tried?",
    "What's one thing you're passionate about?",
    "What's your favorite way to spend time with family?",
    "What's your favorite type of weather?",
    "What's the most inspiring person you've ever met?",
    "What's your favorite way to celebrate a special occasion?",
    "What's your favorite thing to do on a Sunday morning?",
    "What's one thing you couldn't live without?",
    "What's your favorite way to stay healthy?",
    "What's your favorite thing to do when you're feeling stressed?",
    "What's the most beautiful place you've ever seen?",
    "What's your favorite way to learn new skills?",
    "What's your favorite childhood memory?",
    "What's your favorite way to spend time with friends?",
    "What's your favorite way to relax after a long day?",
    "What's the most interesting book you've ever read?",
    "What's your favorite type of music?",
    "What's your favorite way to start the day?",
    "What's your favorite thing about yourself?",
    "What's your favorite way to unwind after a busy day?",
    "What's the best piece of advice you've ever received?",
    "What's your favorite way to spend time outdoors?",
    "What's your favorite way to spend time alone?",
    "What's your favorite thing to do on a Friday night?",
    "What's your favorite type of cuisine?",
    "What's your favorite way to stay active?",
    "What's your favorite thing about your job or school?",
    "What's your favorite thing to do on a sunny day?",
    "What's your favorite way to celebrate a special occasion?",
    "What's your favorite way to meet new people?",
    "What's your favorite thing to do on a lazy day?",
    "What's your favorite childhood memory?",
    "What's your favorite way to express yourself?",
    "What's your favorite thing to do in the winter?",
    "What's your favorite type of weather?",
    "What's your favorite thing about yourself?",
    "What's your favorite thing to do when you're feeling stressed?",
    "What's your favorite way to spend time with family?",
    "What's your favorite type of music?",
    "What's your favorite childhood memory?",
    "What's your favorite way to relax after a long day?",
    "What's your favorite way to start the day?",
    "What's your favorite way to unwind after a busy day?",
    "What's your favorite thing to do on a Friday night?",
    "What's your favorite thing about your job or school?",
    "What's your favorite type of cuisine?",
    "What's your favorite way to stay active?",
    "What's your favorite thing to do on a sunny day?",
    "What's your favorite way to celebrate a special occasion?",
    "What's your favorite way to meet new people?",
    "What's your favorite thing to do on a lazy day?",
    "What's your favorite childhood memory?",
    "What's your favorite way to express yourself?",
    "What's your favorite thing to do in the winter?",
    "What's your favorite type of weather?",
    "What's your favorite thing about yourself?",
    "What's your favorite thing to do when you're feeling stressed?",
    "What's your favorite way to spend time with family?",
    "What's your favorite type of music?"
  ];

  const randomIndex = Math.floor(Math.random() * messages.length);
  return messages[randomIndex];
}

